# GoReleaser configuration for ojs-cli
version: 2

project_name: ojs

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/ojs
    binary: ojs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

archives:
  - format: tar.gz
    name_template: "ojs_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  - name: ojs
    repository:
      owner: openjobspec
      name: homebrew-tap
    description: "CLI for Open Job Spec servers"
    homepage: "https://openjobspec.org"
    license: "Apache-2.0"

nfpms:
  - package_name: ojs
    homepage: https://openjobspec.org
    description: "CLI for Open Job Spec servers"
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
